version: "3"
services:
  db:
    image: postgres:11
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
  app:
    build: ./app
    command: bundle exec ruby app.rb -o 0.0.0.0
    env_file: .env
    ports:
      - 4567:4567
    volumes:
      - ./app:/app
    depends_on:
      - db

